apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: abmdguyzt-go
  janus-idp.io/tekton: abmdguyzt-go
  backstage.io/kubernetes-id: abmdguyzt-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: abmdguyzt-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
